# Generated by Django 2.1 on 2018-10-21 23:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.FloatField(default=0)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(default='test', max_length=600)),
                ('image', models.ImageField(default='2.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='API.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='test', max_length=600)),
                ('rating', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('weekday', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fee', models.FloatField()),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('cancellation_fee', models.FloatField(default=0)),
                ('cancelation_time', models.FloatField(default=0)),
                ('capacity', models.IntegerField()),
                ('off', models.FloatField(default=0)),
                ('firstSans', models.FloatField(default=8)),
                ('lastSans', models.FloatField(default=20)),
                ('restTimeStart', models.FloatField(default=12)),
                ('restTimeEnd', models.FloatField(default=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sans_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('national_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.TimeTable'),
        ),
        migrations.AddField(
            model_name='sans',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.TimeTable'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Users'),
        ),
        migrations.AddField(
            model_name='reserves',
            name='sans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Sans'),
        ),
        migrations.AddField(
            model_name='reserves',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Services'),
        ),
        migrations.AddField(
            model_name='reserves',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Users'),
        ),
        migrations.AddField(
            model_name='pics',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='API.Services'),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Categories'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Users'),
        ),
    ]
