# Generated by Django 2.1.2 on 2018-10-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
