# Generated by Django 2.1.3 on 2019-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sans',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sans',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='cancelation_range',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='services',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
