# Generated by Django 2.1.3 on 2019-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190128_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='cancelation_range',
            new_name='cancellation_range',
        ),
    ]
