# Generated by Django 2.1 on 2018-10-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20181030_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cancelation_time',
        ),
        migrations.RemoveField(
            model_name='services',
            name='cancellation_fee',
        ),
        migrations.RemoveField(
            model_name='services',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='services',
            name='firstSans',
        ),
        migrations.RemoveField(
            model_name='services',
            name='lastSans',
        ),
        migrations.RemoveField(
            model_name='services',
            name='off',
        ),
        migrations.RemoveField(
            model_name='services',
            name='restTimeEnd',
        ),
        migrations.RemoveField(
            model_name='services',
            name='restTimeStart',
        ),
        migrations.AlterField(
            model_name='sans',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sanses', to='API.TimeTable'),
        ),
        migrations.AlterField(
            model_name='services',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='API.Business'),
        ),
    ]
