# Generated by Django 2.1 on 2018-11-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20181031_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetables', to='API.Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='businesses', to='API.Categories'),
        ),
    ]
