# Generated by Django 2.1 on 2018-11-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20181101_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sans',
            old_name='time_table',
            new_name='timetable',
        ),
    ]
