# Generated by Django 2.1 on 2018-11-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20181101_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='business',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Services'),
            preserve_default=False,
        ),
    ]
