# Generated by Django 2.1 on 2018-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20181113_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
