# Generated by Django 2.1.3 on 2018-12-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20181113_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pics',
            name='Business',
        ),
        migrations.RemoveField(
            model_name='pics',
            name='Service',
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Users'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='API.Services'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='API.Users'),
        ),
        migrations.DeleteModel(
            name='pics',
        ),
        migrations.AddField(
            model_name='picture',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='API.Business'),
        ),
        migrations.AddField(
            model_name='picture',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='API.Services'),
        ),
    ]
